name: clean_architecture
description: "Posts App."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Bloc state manager
  flutter_bloc: ^8.1.5

  # Service Locator
  get_it: ^7.7.0

  #Functional Programming
  dartz: ^0.10.1

  # Value equality
  equatable: ^2.0.5

  # Remote Api
  http: ^1.2.1
  internet_connection_checker: ^1.0.0+1

  # Local cache
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
